# Generated by Django 5.0.6 on 2024-10-08 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notification",
            table="Notification",
        ),
    ]
