# Generated by Django 5.0.6 on 2024-10-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_alter_notification_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
