# Generated by Django 5.0.6 on 2024-10-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_alter_notification_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="object_id",
        ),
        migrations.AddField(
            model_name="notification",
            name="related_domain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_object_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
