PUT {{letter-host}}/me/notification/101c6033-2197-47d4-9ffc-deb440595ee1122
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}

{
    "is_read": "True"
}

# GET .나의 알림 가져오기 의-> id 에 해당하는 리소스를 변경
# 