GET {{letter-host}}/letter/5765a1fb-a0a1-4b1e-96e3-7bef306bedca/reply
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}



# letter_id 를 가지고, 해당 letter_id에 답한 letter 가져오기.
# 없으면 없다고 나옴