GET {{letter-host}}/me/letter-box/d5e00a6e-b776-4503-8748-1ccd2455aad6
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}


# 내 letter-box 에 있는 편지 가져오기
# letter_id 를 넣기. letter-box의 id 아닙니다.

