GET {{letter-host}}/letter/b89c6607-519a-4d88-8e93-9615b19c46fe/reply
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}



# letter_id 를 가지고, 해당 letter_id에 답한 letter 가져오기.
# 없으면 없다고 나옴