GET {{letter-host}}/me/letter-box/b89c6607-519a-4d88-8e93-9615b19c46fe
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}


# 내 letter-box 에 있는 편지 가져오기
# letter_id 를 넣기. letter-box의 id 아닙니다.

