GET {{letter-host}}/me/letter-box/78c5f7bf-e5a7-42cf-8e19-157d95f43462/
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}


# 내 letter-box 에 있는 편지 가져오기
# letter box의 id 를 넣기. letter의 id 아닙니다.

