GET {{letter-host}}/letter/c04ffd99-61d9-4fe2-9c76-0d561ab7860d/reply
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}



# letter_id 를 가지고, 해당 letter_id에 답한 letter 가져오기.
# 없으면 없다고 나옴