POST {{letter-host}}/letter/
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}


{
  "to_app_id": "app10",
  "is_anonymous": "False",
  "writing_pad_id": "a6872b3d-a28e-4417-ad8f-49ad449269aa",
  "envelope_id": "8c5750e7-0d7c-4f7d-aee4-41ab7d8d06f5",
  "stamp_id": "b0186622-cd39-4b36-a2ce-3244e9aff93f",
  "content": "reply",
  "title": "To app_001 - reply",
  "font": "NATO_SANS_KR"
}

# 만약 답장이 아니라 편지를 처음 보내는거라면 to_letter_id를 넘겨주지않는다
# 만약 답장인경우 답을 해야하는 편지의 letter_id에 맞게 넘겨준다.
# 이때 to_letter_id의 주인이 to_app_id 여야함. 관련된 기타 예외상황 모두 처리해둠
# {
#   "to_app_id": "app_003",
#   "to_letter_id": "asdasd",
#   "is_anonymous": "False",
#   "writing_pad_id": "Letter1",
#   "envelope_id": "envelope1",
#   "stamp_id": "stamp1",
#   "content": "This is an example letter content. ~~",
#   "title": "To app_002",
#   "font": "NATO_SANS_KR"
# }