GET {{letter-host}}/user/me/?relation=FRIEND&status=ACCEPT
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}

# relation은 친구 외에도 벤, 차단 뭐 등등 있을수도 있고
# status는 친구신청을 했지만 아직 pending인경우, reject 된경우 등등 있습니다.

# 백엔드에 정의된 상수는 다음과같습니다.
# class RelationType(StrEnum):
#     FRIEND = "FRIEND"
#     # 추가 가능


# class RelationStatus(StrEnum):
#     PENDING = "PENDING"
#     REJECT = "REJECT"
#     ACCEPT = "ACCEPT"