PUT {{letter-host}}/me/relationship/
Content-Type: application/json
Authorization: Bearer {{letter-jwt}}

{
    "relation" : "FRIEND",
    "status" : "ACCEPT",   
    "to_app_id": "app1"
}

// 거절은 REJECT 수락은 ACCEPT
