# Generated by Django 5.0.6 on 2024-10-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lucky_letter", "0002_letterrelation_and_more"),
        ("notification", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLetterBox",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                ("is_read", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "UserNotification",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSetting",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("notification_type", models.CharField(max_length=20)),
                ("is_push_allow", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "UserNotificationSetting",
            },
        ),
        migrations.CreateModel(
            name="UserPushToken",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("token", models.CharField(max_length=4096)),
                ("push_service", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserRelation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("relation_type", models.CharField(max_length=36)),
                ("relation_status", models.CharField(max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "UserRelation",
            },
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="User_created_2c9361_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="User_updated_085f8b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="user",
            name="app_id",
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["app_id"], name="User_app_id_88eb63_idx"),
        ),
        migrations.AddField(
            model_name="userletterbox",
            name="letter_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_letter_box_letter_id",
                to="lucky_letter.letter",
            ),
        ),
        migrations.AddField(
            model_name="userletterbox",
            name="user_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_letter_box_user_id",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="notification",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="notification.notification",
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="user_id",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="user_id",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="userpushtoken",
            name="user_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_token_user",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="userrelation",
            name="from_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_relation_from_id",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="userrelation",
            name="to_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_relation_to_id",
                to="user.user",
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mobile_no",
        ),
        migrations.RemoveField(
            model_name="user",
            name="oauth_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="oauth_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tos_agreed",
        ),
    ]
