# Generated by Django 5.0.6 on 2024-09-22 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRelation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("relation_type", models.CharField(max_length=36)),
                ("relation_status", models.CharField(max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "UserRelation",
            },
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="User_created_2c9361_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="User_updated_085f8b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="user",
            name="app_id",
            field=models.CharField(default=None, max_length=16, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["app_id"], name="User_app_id_88eb63_idx"),
        ),
        migrations.AddField(
            model_name="userrelation",
            name="from_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_user_id",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="userrelation",
            name="to_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_user_id",
                to="user.user",
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mobile_no",
        ),
        migrations.RemoveField(
            model_name="user",
            name="oauth_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="oauth_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tos_agreed",
        ),
    ]
