# Generated by Django 5.0.6 on 2024-10-03 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lucky_letter", "0001_initial"),
        ("user", "0002_userrelation_remove_user_user_created_2c9361_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="app_id",
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="UserLetterBox",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                ("is_read", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letter_id",
                    models.ForeignKey(
                        db_constraint=False,
                        max_length=36,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="letter_id",
                        to="lucky_letter.letter",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_constraint=False,
                        max_length=36,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_id",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
