# Generated by Django 5.0.6 on 2024-10-08 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userletterbox_usernotification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usernotification",
            old_name="notification",
            new_name="notification_id",
        ),
    ]
