# Generated by Django 5.0.6 on 2024-10-06 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_app_id_alter_user_name_userletterbox"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userletterbox",
            old_name="letter_id",
            new_name="letter",
        ),
        migrations.RenameField(
            model_name="userletterbox",
            old_name="user_id",
            new_name="user",
        ),
    ]
