# Generated by Django 5.0.6 on 2024-10-06 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_rename_letter_id_userletterbox_letter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userletterbox",
            old_name="letter",
            new_name="letter_id",
        ),
        migrations.RenameField(
            model_name="userletterbox",
            old_name="user",
            new_name="user_id",
        ),
    ]
