# Generated by Django 5.0.6 on 2024-10-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lucky_letter",
            "0007_alter_letter_envelope_id_alter_letter_from_user_id_and_more",
        ),
        ("user", "0006_alter_userletterbox_letter_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userletterbox",
            name="letter_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_letter_box_letter_id",
                to="lucky_letter.letter",
            ),
        ),
        migrations.AlterField(
            model_name="userletterbox",
            name="user_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_letter_box_user_id",
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="userrelation",
            name="from_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_relation_from_id",
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="userrelation",
            name="to_id",
            field=models.ForeignKey(
                db_constraint=False,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_relation_to_id",
                to="user.user",
            ),
        ),
    ]
