# Generated by Django 5.0.6 on 2024-10-07 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_userletterbox_letter_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPushToken",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("token", models.CharField(max_length=4096)),
                ("push_service", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_constraint=False,
                        max_length=36,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_token_user",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
