# Generated by Django 5.0.6 on 2024-10-08 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_userletterbox_letter_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usernotification",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="usernotificationsetting",
            old_name="user",
            new_name="user_id",
        ),
    ]
