# Generated by Django 5.0.6 on 2024-09-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Envelope",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
            options={
                "db_table": "Envelope",
            },
        ),
        migrations.CreateModel(
            name="Stamp",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
            options={
                "db_table": "Stamp",
            },
        ),
        migrations.CreateModel(
            name="WritingPad",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
            options={
                "db_table": "WritingPad",
            },
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("to_app_id", models.CharField(default=None, max_length=36, null=True)),
                ("from_app_id", models.CharField(max_length=36)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("writing_pad_id", models.CharField(max_length=36)),
                ("envelope_id", models.CharField(max_length=36)),
                ("stamp_id", models.CharField(max_length=36)),
                ("content", models.TextField()),
                ("title", models.CharField(max_length=255)),
                ("font", models.CharField(max_length=50)),
                ("will_arrive_at", models.DateTimeField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Letter",
                "indexes": [
                    models.Index(
                        fields=["to_app_id"], name="Letter_to_app__22a26f_idx"
                    ),
                    models.Index(
                        fields=["from_app_id"], name="Letter_from_ap_e2128e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="Letter_created_f0747a_idx"
                    ),
                ],
            },
        ),
    ]
