# Generated by Django 5.0.6 on 2024-10-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lucky_letter", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterRelation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "LetterRelation",
            },
        ),
        migrations.RemoveIndex(
            model_name="letter",
            name="Letter_to_app__22a26f_idx",
        ),
        migrations.RemoveIndex(
            model_name="letter",
            name="Letter_from_ap_e2128e_idx",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="from_app_id",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="to_app_id",
        ),
        migrations.AddField(
            model_name="letter",
            name="from_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_user_id",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="to_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_user_id",
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="envelope_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envelope_id",
                to="lucky_letter.envelope",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="stamp_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stamp_id",
                to="lucky_letter.stamp",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="writing_pad_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="writing_pad_id",
                to="lucky_letter.writingpad",
            ),
        ),
        migrations.AddIndex(
            model_name="letter",
            index=models.Index(fields=["to_user_id"], name="Letter_to_user_7aeebf_idx"),
        ),
        migrations.AddIndex(
            model_name="letter",
            index=models.Index(
                fields=["from_user_id"], name="Letter_from_us_349e98_idx"
            ),
        ),
        migrations.AddField(
            model_name="letterrelation",
            name="reply_letter_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply_letter_id",
                to="lucky_letter.letter",
            ),
        ),
        migrations.AddField(
            model_name="letterrelation",
            name="target_letter_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_letter_id",
                to="lucky_letter.letter",
            ),
        ),
    ]
