# Generated by Django 5.0.6 on 2024-10-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lucky_letter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterGroup",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "LetterGroup",
            },
        ),
        migrations.AddField(
            model_name="letter",
            name="letter_group_id",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddIndex(
            model_name="letter",
            index=models.Index(
                fields=["letter_group_id"], name="Letter_letter__0a681e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lettergroup",
            index=models.Index(
                fields=["created_at"], name="LetterGroup_created_cb98b2_idx"
            ),
        ),
    ]
