# Generated by Django 5.0.6 on 2024-10-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lucky_letter", "0003_letterrelation_delete_lettergroup_and_more"),
        ("user", "0004_rename_letter_id_userletterbox_letter_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="letter",
            name="Letter_to_app__22a26f_idx",
        ),
        migrations.RemoveIndex(
            model_name="letter",
            name="Letter_from_ap_e2128e_idx",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="envelope_id",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="from_app_id",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="stamp_id",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="to_app_id",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="writing_pad_id",
        ),
        migrations.RemoveField(
            model_name="letterrelation",
            name="reply_letter_id",
        ),
        migrations.RemoveField(
            model_name="letterrelation",
            name="target_letter_id",
        ),
        migrations.AddField(
            model_name="letter",
            name="envelope",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lucky_letter.envelope",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="from_user",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="stamp",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lucky_letter.stamp",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="to_user",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="writing_pad",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lucky_letter.writingpad",
            ),
        ),
        migrations.AddField(
            model_name="letterrelation",
            name="reply_letter",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lucky_letter.letter",
            ),
        ),
        migrations.AddField(
            model_name="letterrelation",
            name="target_letter",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lucky_letter.letter",
            ),
        ),
        migrations.AddIndex(
            model_name="letter",
            index=models.Index(fields=["to_user"], name="Letter_to_user_27bf42_idx"),
        ),
        migrations.AddIndex(
            model_name="letter",
            index=models.Index(fields=["from_user"], name="Letter_from_us_c3b676_idx"),
        ),
    ]
