# Generated by Django 5.0.6 on 2024-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lucky_letter", "0004_remove_letter_letter_to_app__22a26f_idx_and_more"),
        ("user", "0005_rename_letter_userletterbox_letter_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="letter",
            name="Letter_to_user_27bf42_idx",
        ),
        migrations.RemoveIndex(
            model_name="letter",
            name="Letter_from_us_c3b676_idx",
        ),
        migrations.RenameField(
            model_name="letter",
            old_name="envelope",
            new_name="envelope_id",
        ),
        migrations.RenameField(
            model_name="letter",
            old_name="from_user",
            new_name="from_user_id",
        ),
        migrations.RenameField(
            model_name="letter",
            old_name="to_user",
            new_name="to_user_id",
        ),
        migrations.RenameField(
            model_name="letter",
            old_name="writing_pad",
            new_name="writing_pad_id",
        ),
        migrations.RenameField(
            model_name="letterrelation",
            old_name="reply_letter",
            new_name="reply_letter_id",
        ),
        migrations.RenameField(
            model_name="letterrelation",
            old_name="target_letter",
            new_name="target_letter_id",
        ),
        migrations.AddIndex(
            model_name="letter",
            index=models.Index(fields=["to_user_id"], name="Letter_to_user_7aeebf_idx"),
        ),
        migrations.AddIndex(
            model_name="letter",
            index=models.Index(
                fields=["from_user_id"], name="Letter_from_us_349e98_idx"
            ),
        ),
    ]
