# Generated by Django 5.0.6 on 2024-10-06 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lucky_letter", "0005_remove_letter_letter_to_user_27bf42_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="letter",
            old_name="stamp",
            new_name="stamp_id",
        ),
    ]
