# Generated by Django 5.0.6 on 2024-10-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lucky_letter", "0006_rename_stamp_letter_stamp_id"),
        ("user", "0006_alter_userletterbox_letter_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="envelope_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envelope_id",
                to="lucky_letter.envelope",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="from_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_user_id",
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="stamp_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stamp_id",
                to="lucky_letter.stamp",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="to_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_user_id",
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="writing_pad_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="writing_pad_id",
                to="lucky_letter.writingpad",
            ),
        ),
        migrations.AlterField(
            model_name="letterrelation",
            name="reply_letter_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply_letter_id",
                to="lucky_letter.letter",
            ),
        ),
        migrations.AlterField(
            model_name="letterrelation",
            name="target_letter_id",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_letter_id",
                to="lucky_letter.letter",
            ),
        ),
    ]
